version: '2.1'
services:
  mapserver:
    image: camptocamp/mapserver:7.4
    restart: unless-stopped

  rabbitmq:
    image: library/rabbitmq

  worker:
    build: django
    hostname: worker
    command: celery worker -A fba -l info --beat
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.prod_docker
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASS=${POSTGRES_PASS}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - MAPSERVER_PUBLIC_WMS_URL=${MAPSERVER_PUBLIC_WMS_URL}
      - MAPSERVER_PUBLIC_OWS_URL=${MAPSERVER_PUBLIC_OWS_URL}
      - MAPSERVER_PUBLIC_SLD_URL=${MAPSERVER_PUBLIC_SLD_URL}
      - POSTGREST_BASE_URL=${POSTGREST_BASE_URL}
    volumes:
      - ./fixtures:/home/web/fixtures
      - ./django/django_project:/home/web/django_project
      - ./django/volumes/static:/home/web/static
      - ./django/volumes/media:/home/web/media
      - ./django/volumes/logs:/var/log/
      - ./django/volumes/data:/home/web/data
    links:
      - mapserver:mapserver
      - rabbitmq:rabbitmq

  django-uwsgi:
    # Note you cannot scale if you use container_name
    build: django
    image: project_uwsgi
    command: uwsgi --ini /home/web/django_project/uwsgi.conf
    environment:
      DJANGO_SETTINGS_MODULE: core.settings.prod_docker
      VIRTUAL_HOST: project.com
      VIRTUAL_PORT: 8080
      MAPSERVER_PUBLIC_WMS_URL: ${MAPSERVER_PUBLIC_WMS_URL}
      MAPSERVER_PUBLIC_OWS_URL: ${MAPSERVER_PUBLIC_OWS_URL}
      MAPSERVER_PUBLIC_SLD_URL: ${MAPSERVER_PUBLIC_SLD_URL}
      POSTGREST_BASE_URL: ${POSTGREST_BASE_URL}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASS: ${POSTGRES_PASS}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    volumes:
      - ./fixtures:/home/web/fixtures
      - ./django/django_project:/home/web/django_project
      - ./django/volumes/static:/home/web/static
      - ./django/volumes/media:/home/web/media
      - ./django/volumes/logs:/var/log/
      - ./django/volumes/data:/home/web/data
    links:
      - mapserver:mapserver
      - rabbitmq:rabbitmq

  # This is normally the main entry point for a production server
  django-web:
    # Note you cannot scale if you use container_name
    image: nginx
    hostname: nginx
    volumes:
      - ./django/sites-enabled:/etc/nginx/conf.d:ro
      # I dont use volumes_from as I want to use the ro modifier
      - ./django/volumes/static:/home/web/static:ro
      - ./django/volumes/media:/home/web/media:ro
      - ./django/volumes/data:/home/web/data:ro
      - ./django/volumes/logs:/var/log/nginxs
    links:
      - django-uwsgi:uwsgi
      - mapserver:mapserver
      - rabbitmq:rabbitmq
    restart: on-failure:5
